version: "3.9"

services:
  base:
    build:
      context: .
      target: base
    volumes:
      - ".:/pycapnp"
  development:
    build:
      context: .
      target: development
    volumes:
      - ".:/pycapnp"
    stdin_open: true
    tty: true
  test:
    build:
      context: .
      target: test
    volumes:
      - ".:/pycapnp"
